name = "scrabble-study-sync"
main = "index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "scrabble-study-db"
database_id = "6d162738-a6d0-46f9-bdfc-d16fccc32259"
